name: EduSpark CI/CD Pipeline

on:
  push:
    branches: [ master ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: pytest

      - name: Build Docker image
        run: docker build -t eduspark-app .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Tag Docker image
        run: docker tag eduspark-app ${{ secrets.DOCKER_USERNAME }}/eduspark-app:latest

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/eduspark-app:latest
